apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: prisma
  name: prisma
spec:
  ports:
  - name: "4466"
    port: 4466
    targetPort: 4466
  selector:
    io.kompose.service: prisma
status:
  loadBalancer: {}
