apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  type:  NodePort
  ports:
  - name: "4000"
    port: 4000
    nodePort: 30001
    targetPort: 4000
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
