version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: 35.228.93.80
            port: 3306
            user: planaprisma
            password: PASSWORD
            migrations: true
  # server:
  #   restart: always
  #   image: stilrenw/planaserver
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - "prisma"
  assignment:
    restart: always
    image: stilrenw/planaassignment
    ports:
      - "8000:80"
  # client:
  #   restart: always
  #   image: stilrenw/planaclient
  #   ports:
  #     - 80:3000
