version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: 35.228.93.80
            port: 3306
            user: planaprisma
            password: PASSWORD
            migrations: true
