version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    # ports:
    #   - "4466:4466"
    expose:
      - "4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: 35.228.93.80
            port: 3306
            user: planaprisma
            password: PASSWORD
            migrations: true
  planaserver:
    restart: always
    image: stilrenw/planaserver
    # ports:
    #   - "4000:4000"
    expose:
      - "4000"
    links:
      - "prisma:prisma"
      - "assignment:assignment"
    depends_on:
      - "prisma"
  assignment:
    restart: always
    image: stilrenw/planaassignment
    # ports:
    #   - "8000:80"
    expose:
      - "80"
  planaclient:
    restart: always
    image: stilrenw/planaclient
    expose:
      - "3000"
    # ports:
    #   - 80:3000
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - "planaserver"
      - "planaclient"
